name = PropertiesConfig

# Console Appender
appender.console.type = Console
appender.console.name = consoleLogger
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{HH:mm:ss}]-[%5p ]-[%msg]%n

# File Appender
appender.FILE.type = File
appender.FILE.name = fileAppender
appender.FILE.fileName = logs/general.log
appender.FILE.layout.type = PatternLayout
appender.FILE.layout.pattern = [%d{HH:mm:ss}]-[%5p ]-[%msg]%n

# Root Logger
rootLogger.level = debug
rootLogger.appenderRef.console.ref = consoleLogger
rootLogger.appenderRef.file.ref = fileAppender